# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: www.after5notary.com
title: After 5 Notary
email: info@after5notary.com
author: Sierra Davis
description: > # "Write an awesome description for your new site here. 
  Providing reliable mobile Notary Services in the Kansas City area. Appointments available after 5pm.
copyright: 'Copyright &copy; 2020 After 5 Notary. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: calendar
    url: https://freebusy.io/essentialinvestmentgrp@gmail.com
 # - title: github
   # url: https://github.com/IronSummitMedia/startbootstrap
 # - title: linkedin
  #  url: 
